### ISSUE TITLE
How to generate array with referenceByClass?

### ISSUE THREAD

**Issue by dianxin11** [AaronJan/Kobe#4]
Hi,
I'm a newbie on swagger, I want to generate the json code like this:

                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Pet"
                            }
                        }
                    },
                },

I try to this 'data' => Kobe::referenceByClass(Pet::class)->toArray()  but isn't work.
What should I do?
Thanks!

**Comment by AaronJan** [comment]
Hi, dianxin11, you can try this:

```php
Kobe::makeArray()->setReferenceAsItems(Kobe::referenceByClass(Pet::class))
```

Let me know if you solve this.

**Comment by dianxin11** [comment]
Thanks a lot, it worked!
